volumes:
  postgres_data:
  pgadmin_data:

secrets:
  pgpassword:
    file: ./secrets/pgpassword.txt
  pgadmin:
    file: ./secrets/pgadmin.txt

services:
  postgres:
    image: docker.io/postgres:14-alpine
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_PASSWORD_FILE: /run/secrets/pgpassword
    secrets:
      - pgpassword

  pgadmin:
    image: docker.io/dpage/pgadmin4:snapshot
    environment:
      PGADMIN_DISABLE_POSTFIX: "1"
      PGADMIN_DEFAULT_EMAIL: "$PGADMIN_DEFAULT_EMAIL"
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin
      PGADMIN_SERVER_JSON_FILE: /config/servers.json
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
      - "./pgadmin:/config"
    ports:
      - "8000:80"
    secrets:
      - pgadmin
